name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'

runs:
  using: "composite"
  steps:
    - uses: provicapital/deploy-onep@master
      env:
          url: $ONEP_DEPLOY_URL
          id: ${{ secrets.ONEP_APP_ID }}
          uid: ${{ secrets.ONEP_APP_UID }}
          org: ${{ secrets.ONEP_ORG }} 
    - run: |
        curl --request POST \
            --url $url \
            --header 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
              "application_id": $id,
              "application_uid": "$uid",
              "organization": "$org",
              "description": "${{ github.event.head_commit.message }}",
              "version": "${{ github.sha }}",
              "type": "deploy"
            }
            EOF
      shell: bash