name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'provicapital'
inputs:
  onep-deploy-url:
    description: >-
      URL used for webhook with One Platform
    required: false
  onep-app-id:
    description: >-
      URL used for webhook with One Platform
    required: false
  onep-app-uid:
    description: >-
      URL used for webhook with One Platform
    required: false
  onep-org:
    description: >-
      URL used for webhook with One Platform
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        curl --request POST \
            --url $url \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $id,
                "application_uid": "$uid",
                "organization": "$org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF'
      shell: bash