name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'
runs:
  using: "composite"
  steps:
    - run: provicapital/deploy-onep/src/register-deploy.sh
      shell: bash