name: 'deploy-onep'
description: 'Register deploy with One Platform!'
runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url https://apis.elven.works/external/v1/deploy/9d7ceb24-0f3b-40d0-b6db-965b92c3e299?token=HbBIWutY3XPRLUtXMATPrGTC0NHRGQez \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": 8688,
                "application_uid": "9d7ceb24-0f3b-40d0-b6db-965b92c3e299",
                "organization": "fe391bb6-1b58-421c-9f1b-d8167792fa8b",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF       
      shell: bash