name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'

runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url $url \
            --header 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $onep.app.id,
                "application_uid": "$onep.app.uid",
                "organization": "$ONEP_ORG",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF
      shell: bash