name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'

runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url https://apis.elven.works/external/v1/deploy/9d7ceb24-0f3b-40d0-b6db-965b92c3e299?token=HbBIWutY3XPRLUtXMATPrGTC0NHRGQez \
            -H 'Content-Type: application/json' \
            --data-binary @- << EOF
            {
                "application_id": $ONEP_DEPLOY_URL,
                "application_uid": "$onep.app.uid",
                "organization": "$onep.org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF
      shell: bash