name: 'deploy-onep'
description: 'Register deploy with One Platform!'
runs:
  using: "composite"
  steps:
    - run: |
        chmod +x src/register-deploy.sh
        sh src/register-deploy.sh       
      shell: bash