name: 'deploy-onep'
description: 'Register deploy with One Platform!'
runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url https://apis.elven.works/external/v1/deploy/9d7ceb24-0f3b-40d0-b6db-965b92c3e299?token=HbBIWutY3XPRLUtXMATPrGTC0NHRGQez \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": ${{ secrets.ONEP_APP_ID }},
                "application_uid": "${{ secrets.ONEP_APP_UID }}",
                "organization": "${{ secrets.ONEP_ORG }}",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF       
      shell: bash