name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'provicapital'
inputs:
  onep-deploy-url:
    description: >-
      URL used for webhook with One Platform
    required: false
  onep-app-id:
    description: >-
      App ID used for webhook with One Platform
    required: false
  onep-app-uid:
    description: >-
      User ID used for webhook with One Platform
    required: false
  onep-org:
    description: >-
      Org used for webhook with One Platform
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        curl --request POST \
            --url '$onep-deploy-url' \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $onep-app-id,
                "application_uid": "$onep-app-uid",
                "organization": "$onep-org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF'
      shell: bash