name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'
runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url $onep_deploy_url \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $onep_app_id,
                "application_uid": "$onep_app_id",
                "organization": "$onep_org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF
      shell: bash