name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'

runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url $onep-url \
            --header 'Content-Type: application/json' \
            --data '{
                "application_id": $onep-app-id,
                "application_uid": "$onep-app-uid",
                "organization": "$onep-org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }'
      shell: bash