name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'Douglas Silva'
runs:
  using: "composite"
  steps:
    - run: |
        curl --request POST \
            --url $ONEP_DEPLOY_URL \
            -header 'Content-Type: application/json' \
            --data '{
                "application_id": $ONEP_APP_ID,
                "application_uid": "$ONEP_APP_UID",
                "organization": "$ONEP_ORG",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }'
      shell: bash