name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'provicapital'

runs:
  using: 'composite'
  steps:
    - run: |
        curl --request POST \
            --url $url \
            --header 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $id,
                "application_uid": "$uid",
                "organization": "$org",
                "description": "${{ github.event.head_commit.message }}"",
                "version": "${{ github.sha }}"",
                "type": "deploy"
            }
            EOF'
      shell: bash