name: 'deploy-onep'
description: 'Register deploy with One Platform!'
author: 'provicapital'
inputs:
  url:
    description: 'URL do register deploy'
    default: ${{ ONEP_DEPLOY_URL }}
    required: false
  id:
    description: 'App ID for register deploy'
    default: ${{ ONEP_APP_ID }}
    required: false
  uid:
    description: 'App UID for register deploy'
    default: ${{ ONEP_APP_UID }}
    required: false
  org:
    description: 'Organization name for register deploy'
    default: ${{ ONEP_ORG }}
    required: false

runs:
  using: 'composite'
  steps:
    - run: |
        curl --request POST \
            --url $url \
            -H 'Content-Type: application/json' \
            --data-binary @- <<EOF
            {
                "application_id": $id,
                "application_uid": "$uid",
                "organization": "$org",
                "description": "${{ github.event.head_commit.message }}",
                "version": "${{ github.sha }}",
                "type": "deploy"
            }
            EOF'
      shell: bash