on:
  push:
    branches: [ master ]

name: Run tests
jobs:
  aws_copilot_ci:
    name: AWS Copilot CI Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS credentials - Staging account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_COPILOT }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_COPILOT }}
          aws-region: us-east-3